apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: gcr.io/google-samples/microservices-demo/adservice:v0.2.3
        env:
        - name: PORT
          value: "9555"
        ports:
        - containerPort: 9555

---

apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  selector:
    app.kubernetes.io/name: adservice
  ports:
    - protocol: TCP
      port: 9555
      targetPort: 9555