apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.2.3
        env:
        - name: PORT
          value: "50051"
        ports:
        - containerPort: 50051

---

apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  selector:
    app.kubernetes.io/name: paymentservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051