apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis-cart
        image: redis:alpine
        env:
        - name: PORT
          value: "6379"
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  selector:
    app.kubernetes.io/name: redis-cart
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379