apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.3
        env:
        - name: PORT
          value: "50051"
        ports:
        - containerPort: 50051

---

apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  selector:
    app.kubernetes.io/name: shippingservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051